version: '3.8'

services:

  mongo_db:
    container_name : node-refapp-mongo-docker
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - '9005:27017'

  node-refapp:
    container_name: node-refapp-docker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - '3000'
    ports:
      - '9004:3000'
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
